Repository ilmhub-uz/FurnitureShop, pull requests merged in 2022-12, with the labels that each got.

#14 Leverow/Update product dto validator added
  FurnitureShop/src/FurnitureShop.Admin.Api/Dtos/UpdateProductDto.cs
  FurnitureShop/src/FurnitureShop.Admin.Api/Validators/UpdateProductDtoValidator.cs
Labels: Status: Review needed 👁

#13 Botirjon/GetOrdersByFilter
  FurnitureShop/src/FurnitureShop.Admin.Api/Dtos/OrderFilter.cs
  FurnitureShop/src/FurnitureShop.Admin.Api/Services/IOrdersService.cs
  FurnitureShop/src/FurnitureShop.Admin.Api/Services/OrdersService.cs
Labels: ⚠️ depends on pagination ⚠️, DO NOT MERGE ❌, Status: Review needed 👁

#89 Exists method added
  FurnitureShop/src/FurnitureShop.Data/Repositories/ConcreteTypeRepositories/ProductRepository.cs
  FurnitureShop/src/FurnitureShop.Data/Repositories/GenericRepository.cs
  FurnitureShop/src/FurnitureShop.Data/Repositories/IEntityExistsRepository.cs
Labels: Status: Review needed 👁

#91 Leverow/ Added Id checker action filter attribute
  FurnitureShop/src/FurnitureShop.Common/Filters/IdCheckerAttribute.cs
  FurnitureShop/src/FurnitureShop.Common/Filters/IdValidationAttribute.cs
Labels: Status: Review needed 👁

#93 Leverow/Dashboard ui Signin page and loader added
  FurnitureShop/front/FurnitureShop.Admin.Blazor/Pages/Signin.razor
  FurnitureShop/front/FurnitureShop.Admin.Blazor/wwwroot/assets/css/dashboard.custom.css
  FurnitureShop/front/FurnitureShop.Admin.Blazor/wwwroot/index.html
Labels: Project: Dashboard UI, Status: Review needed 👁

#110 added validators, removed unnecessary dtos
  FurnitureShop/src/FurnitureShop.Merchant.Api/Dtos/CreateCategoryDto.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Dtos/CreateProductDto.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Dtos/UpdateCategoryDto.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Dtos/UpdateProductDto.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Validators/CreateProductDtoValidator.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Validators/UpdateProductDtoValidator.cs
Labels: Status: Review needed 👁

#114 vaidation implementation
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/ProductsController.cs
Labels: Status: Review needed 👁

#94 Muhammad-Diyor/FurnitureShop.Merchant/Added-IManagerService
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/IEmployeesService.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/ViewModel/GetEmployeesView.cs
Labels: Status: Review needed 👁

#96 Muhammad-Diyor/FurnitureShop.Merchant/ManagerService
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/EmployeeService.cs
Labels: DO NOT MERGE ❌, Status: Review needed 👁

#168 Umid/IEntityExistsRepository added to ProductImageRepository
  FurnitureShop/src/FurnitureShop.Data/Repositories/ConcreteTypeRepositories/ProductImageRepository.cs
Labels: Status: Review needed 👁

#169 IEntityExistsRepository Added To OrganizationRepository
  FurnitureShop/src/FurnitureShop.Data/Repositories/ConcreteTypeRepositories/OrganizationRepository.cs
Labels: Status: Review needed 👁

#170 IEntityExistsRepository Added To OrderRepository
  FurnitureShop/src/FurnitureShop.Data/Repositories/ConcreteTypeRepositories/OrderRepository.cs
Labels: Status: Review needed 👁

#171 IEntityExistsRepository Added To FavoriteRepository
  FurnitureShop/src/FurnitureShop.Data/Repositories/ConcreteTypeRepositories/FavoriteRepository.cs
Labels: Status: Review needed 👁

#172 IEntityExistsRepository Added To CategoryRepository
  FurnitureShop/src/FurnitureShop.Data/Repositories/ConcreteTypeRepositories/CategoryRepository.cs
Labels: Status: Review needed 👁

#173 IEntityExistsRepository Added To CartRepository
  FurnitureShop/src/FurnitureShop.Data/Repositories/ConcreteTypeRepositories/CartRepository.cs
Labels: Status: Review needed 👁

#174 IEntityExistsRepository Added To AppUserRepository
  FurnitureShop/src/FurnitureShop.Data/Repositories/ConcreteTypeRepositories/AppUserRepository.cs
Labels: Status: Review needed 👁

#182 IdValidationAttribute added to ProductService
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/ProductService.cs
Labels: Status: Review needed 👁

#186 IdValidationAttribute added to OrganizationService
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/OrganizationService.cs
Labels: Status: Review needed 👁

#191 IdValidationAttribute added to ContractService
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/ContractService.cs
Labels: Status: Review needed 👁

#221 Username validatsiyasi muvaffaqiyatli o'rnatildi
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/AccountController.cs
Labels: Status: Review needed 👁

#223 IdValidation Merchant ProductService classlaridan o'chirilib Merchant…
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/ContractsController.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/OrganizationsController.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/ProductsController.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/OrganizationService.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/ProductService.cs
Labels: Status: Review needed 👁

#238 Merchant ProductController RateProduct actioni kamchiliklari to'g'irlandi
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/ProductsController.cs
Labels: Status: Review needed 👁

#251 productni update qilayotgan userning u productga access i bor yo'qligi tekshirishadigan qoshildi
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/ProductsController.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/IProductService.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Services/ProductService.cs
Labels: Status: Review needed 👁

#252 Merchant Controllerlarining bazi action parameterlariga frombody attributi qo'yildi
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/EmployeeController.cs
  FurnitureShop/src/FurnitureShop.Merchant.Api/Controllers/ProductsController.cs
Labels: Status: Review needed 👁

#270 [Dashboard-UI] Some changes
  FurnitureShop/front/FurnitureShop.Admin.Blazor/Pages/Organizations.razor
Labels: Status: Review needed 👁

#296 Changed /account/login redirection to UnAuthorized response status code
  FurnitureShop/src/FurnitureShop.Common/Extensions/ServiceCollectionExtensions.cs
Labels: Status: Review needed 👁

#305 Leverow/Get user avatar endpoint
  FurnitureShop/src/FurnitureShop.Files.Api/Controllers/FilesController.cs
  FurnitureShop/src/FurnitureShop.Files.Api/FurnitureShop.Files.Api.csproj
  FurnitureShop/src/FurnitureShop.Files.Api/Program.cs
  FurnitureShop/src/FurnitureShop.Files.Api/Services/FileService.cs
  FurnitureShop/src/FurnitureShop.Files.Api/Services/IFileService.cs
Labels: Status: Review needed 👁, GLOBAL

#307 Leverow/ Fixed admin api Program.cs
  FurnitureShop/front/FurnitureShop.Admin.Blazor/Shared/MainLayout.razor
  FurnitureShop/front/FurnitureShop.Admin.Blazor/wwwroot/index.html
  FurnitureShop/src/FurnitureShop.Admin.Api/Controllers/ProfilesController.cs
  FurnitureShop/src/FurnitureShop.Admin.Api/Program.cs
Labels: Status: Review needed 👁

#310 merchant's blazor modified
  FurnitureShop/front/FurnitureShop.Merchant.Blazor/Pages/Organization.razor
  FurnitureShop/front/FurnitureShop.Merchant.Blazor/Pages/Organizations.razor
Labels: Status: Review needed 👁
